-- 최소 스키마 (DROP 후 재생성 테스트용)
SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS role;
CREATE TABLE role (id BIGINT PRIMARY KEY AUTO_INCREMENT, role_code VARCHAR(50));
SET REFERENTIAL_INTEGRITY TRUE;
